apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-quarkus-colors
  name: my-quarkus-colors
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-quarkus-colors
status:
  loadBalancer: {}
